/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FormatActions: typeof import('./src/components/extensions/VDataTable/FormatActions.vue')['default']
    FormatDateTime: typeof import('./src/components/extensions/VDataTable/FormatDateTime.vue')['default']
    FormatHover: typeof import('./src/components/extensions/VDataTable/FormatHover.vue')['default']
    FormatLink: typeof import('./src/components/extensions/VDataTable/FormatLink.vue')['default']
    FormatPrice: typeof import('./src/components/extensions/VDataTable/FormatPrice.vue')['default']
    FormatSetting: typeof import('./src/components/extensions/VDataTable/FormatSetting.vue')['default']
    FormatStatus: typeof import('./src/components/extensions/VDataTable/FormatStatus.vue')['default']
    FormatSwitch: typeof import('./src/components/extensions/VDataTable/FormatSwitch.vue')['default']
    FormatType: typeof import('./src/components/extensions/VDataTable/FormatType.vue')['default']
    MarkdownCard: typeof import('./src/components/MarkdownCard.vue')['default']
    MarkdownTest: typeof import('./src/components/MarkdownTest.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
    VBarChart: typeof import('./src/components/chart/VBarChart.vue')['default']
    VCustomCard: typeof import('./src/components/general/VCustomCard.vue')['default']
    VCustomLayout: typeof import('./src/components/general/VCustomLayout.vue')['default']
    VDataTable: typeof import('./src/components/general/VDataTable.vue')['default']
    VDateSelect: typeof import('./src/components/general/VDateSelect.vue')['default']
    VDeletionAlert: typeof import('./src/components/general/VDeletionAlert.vue')['default']
    VDialogLayout: typeof import('./src/components/general/VDialogLayout.vue')['default']
    VFilterGroupSelect: typeof import('./src/components/general/VFilterGroupSelect.vue')['default']
    VFilterSelect: typeof import('./src/components/general/VFilterSelect.vue')['default']
    VFilterSelectLayout: typeof import('./src/components/general/VFilterSelectLayout.vue')['default']
    VGaugeChart: typeof import('./src/components/chart/VGaugeChart.vue')['default']
    VLabel: typeof import('./src/components/general/VLabel.vue')['default']
    VLineChart: typeof import('./src/components/chart/VLineChart.vue')['default']
    VMultipleGroupSelect: typeof import('./src/components/general/VMultipleGroupSelect.vue')['default']
    VMultipleSelect: typeof import('./src/components/general/VMultipleSelect.vue')['default']
    VPieChart: typeof import('./src/components/chart/VPieChart.vue')['default']
    VTextInput: typeof import('./src/components/general/VTextInput.vue')['default']
  }
}
