import type { ColorVariables } from '@/declarations/Theme'
const {
  primaryBlue,
  primaryDarkBlue,
  primaryGreen,
  primaryOrange,
  highlightRed,
  highlightGreen,
  gray0,
  gray20,
  gray30,
  gray40,
  gray50,
  gray60,
  gray80,
  gray90,
  gray100
}: ColorVariables = {
  primaryBlue: '#73BCFF',
  primaryDarkBlue: '#003A70',
  primaryGreen: '#78D7DD',
  primaryOrange: '#FFB46F',
  highlightRed: '#FF6C7E',
  highlightGreen: '#2ED4AC',
  gray0: '#F0F0F0',
  gray20: '#B4B4B4',
  gray30: '#8598AA',
  gray40: '#627D97',
  gray50: '#394552',
  gray60: '#353F49',
  gray80: '#2A333B',
  gray90: '#EDEEEE',
  gray100: '#1E282C'
}

export const darkColors = {
  white: gray0,
  black: gray100,
  'primary-blue': primaryBlue,
  'on-primary-blue': gray80,
  'primary-dark-blue': primaryDarkBlue,
  'on-primary-dark-blue': gray0,
  'primary-green': primaryGreen,
  'primary-orange': primaryOrange,
  'highlight-red': highlightRed,
  'highlight-green': highlightGreen,
  'gray-0': gray0,
  'gray-20': gray20,
  'gray-30': gray30,
  'on-gray-30': gray0,
  'gray-40': gray40,
  'on-gray-40': gray0,
  'gray-50': gray50,
  'on-gray-50': gray0,
  'gray-60': gray60,
  'on-gray-60': gray0,
  'gray-80': gray80,
  'on-gray-80': gray0,
  'gray-90': gray90,
  'on-gray-90': gray0,
  'gray-100': gray100,
  'on-gray-100': gray0,
  error: highlightRed,
  'on-error': gray80,
  info: primaryBlue,
  success: highlightGreen,
  warning: primaryOrange,
  header: primaryBlue,
  'on-header': gray100,
  sidemenu: gray60,
  'on-sidemenu': gray0,
  'sidemenu-group': gray100,
  'on-sidemenu-group': gray0,
  'sidemenu-icon': gray40,
  'sidemenu-selected': gray40,
  card: gray60,
  'on-card': gray0,
  table: gray60,
  'on-table': gray0,
  'table-pagination-selected': gray40,
  'on-table-pagination-selected': gray100,
  alert: gray60,
  'on-alert': gray20,
  'alert-title': gray0,
  dialog: gray60,
  'on-dialog': gray0,
  tab: gray100,
  'on-tab': gray20,
  'tab-selected': gray60,
  'on-tab-selected': gray0,
  filter: gray100,
  'on-filter': gray0,
  label: gray50,
  'on-label': gray20,
  dropdown: gray100,
  'on-dropdown': gray0,
  field: gray100,
  'on-field': gray0,
  tooltip: gray80,
  'on-tooltip': gray0,
  'expansion-group': gray30,
  'on-expansion-group': gray100,
  mdeditor: gray100,
  mdtoolbar: gray50,
  mdborder: gray50,
  mdcode: gray100,
  'on-mdcode': gray30,
  mdmodalbody: gray60,
  'on-mdmodalbody': gray0,
  mdmodalinput: gray100,
  stepper: gray80,
  'on-stepper': primaryBlue,
  'on-date-picker': gray0
}
